export enum A_PRODUCTS_TYPES__AppStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    MAINTENANCE = 'MAINTENANCE',
    SUSPENDED = 'SUSPENDED',
    TESTING = 'TESTING',
}